#!/usr/bin/env node
/* Generates js/data.js — the receivables dataset embedded as an ES module so the
 * app also works from file:// (no fetch, no CORS, no server required).
 * Usage: node tools/gen-data.js   (run from the saas/ directory) */
import { readFileSync, writeFileSync } from 'node:fs';

const csv = readFileSync(new URL('../data/receivables.csv', import.meta.url), 'utf8');
const out = `/* AUTO-GENERATED by tools/gen-data.js — do not edit by hand.
 * Source of truth: saas/data/receivables.csv
 * Regenerate with: node tools/gen-data.js
 */
export const CSV = ${JSON.stringify(csv)};
export const GENERATED_AT = ${JSON.stringify(new Date().toISOString())};
export const SOURCE_FILE = 'saas/data/receivables.csv';
`;
writeFileSync(new URL('../js/data.js', import.meta.url), out);
console.log(`wrote js/data.js (${out.length} bytes, ${csv.split('\n').filter(Boolean).length - 1} data rows)`);
